- src/app/modules/account/pages/confirmation/confirmation.component.html
- src/app/modules/account/pages/confirmation/confirmation.component.ts
- src/app/modules/account/pages/sending/sending.component.ts
Hi Sam,
This is the bug fix for the JIRA ticket DEAM-92. I would like to ask for you quick code review before merging this to msp-deam branch. In this PR:
- Third blue box is displaying now when the user has added a spouse with No previous MSP
- Added a header "Next Steps" above the blue box
Regards,
Cyril
> Fixed bug for the third box in Confirmation Page

- src/app/modules/account/pages/contact-info/contact-info.component.html
- src/app/styles/overrides.scss
I couldn't apply the custom styling to the `common-checkbox` component without heavily modifying the  common library. So I've removed the custom checkbox styling and replaced it with the native `common-checkbox` (the size has also been increased).
> DEAM-122: Replace custom checkbox with native checkbox

- src/app/modules/account/services/msp-api-account.service.ts
This is a hack to remove the `_sequence` attribute populated in the JSON payload object. The form now submits successfully.
> Remove sequence from JSON payload.

- src/app/modules/account/components/update-request/update-request.component.html
- src/app/modules/account/pages/child-info/update-child/update-child.component.html
What I did:
1) Changed `correct` to `update` where requested
2) Add missing options and document slots for update-child component
3) Reorder options to follow suit with update-request (used for AH and
spouse)
>## Screenshots of old version:
>## Screenshots of new version:
> DEAM-309: Change gender desig. labels, add options

- src/app/modules/account/pages/home/home.component.scss
IE needed width to be explicit in children of flex container and Firefox
doesn't recognize `auto` for padding in certain situations so
that was handled as well.
>## Screenshots of new version across all major browsers:
> DEAM-321: Home page browser cross-compatibility

- src/app/modules/account/components/moving-information/moving-information.component.html
- src/app/modules/account/components/moving-information/moving-information.component.ts
- src/app/modules/account/pages/child-info/child-info.component.ts
Very basic validation for removed and added children, date validation
for 12 and 6 month departure and return dates is working, but there remains a
slightly annoying issue where if both dates are invalid, you have to
fix both then click off of both before the error goes away. Leaving
this in favour of working on higher priority issues
> DEAM-291: More validation for child-info

- src/app/modules/account/components/moving-information/moving-information.component.html
- src/app/modules/account/services/msp-api-account.service.ts
What I did:
1) Stop console errors by adding missing name attributes to ngModel
bindings
2) Temporarily remove use of date formatter in msp-api-account service
(in method `populateNewBeneficiaryDetailsForChild`)
The failure on submission was for the 31 days or more out of province fields (6 months in future, last 12 months) and was only happening for child.
> DEAM-329: Prevent error on submission for child

- src/app/modules/account/pages/home/home.component.html
- src/app/modules/account/pages/home/home.component.scss
What I did:
1) Line up paragraphs with container edge
2) Match font size in alert box
3) Line up horizontal line with contents of container
4) Line up bottoms of options containers
5) Shorten class names
Tested on IE, Edge, Firefox, and Chrome, see attached screenshots:
> DEAM-340: Fix font size and other issues on home

- src/app/modules/account/components/moving-information/moving-information.component.html
- src/app/modules/account/services/msp-api-account.service.ts
What I did:
1) Fix incorrect ngModel attrs
2) Add the following missing items to child PDF output:
- Outside province info (reasons, destinations, dates, boolean)
- Lived in BC info (dates, booleans, previous health number)
- School info (name, address, dates)
The JSON looks fairly complete now, but I think there may be a small issue with the willBeAway field. If you a child is both discharged from military service and away for school, fulltimeStudent will be set to "N". I'm not sure if the actual situation is even possible or all the different sorts of discharge the discharge field can refer to but it's possibly an issue.
Attached is previous (incomplete) JSON and new (complete) JSON, zipped
[payloads.zip](https://github.com/bcgov/MyGovBC-MSP/files/4918367/pa …
> DEAM-268: Get missing child dates, info into PDF

- src/app/modules/account/components/personal-information/personal-information.component.ts
- src/app/modules/account/pages/child-info/add-child/add-child.component.html
What I did:
1) Switching to ngModel as opposed to value and value change function
(as recommended by K). This fixed an issue I had just found where
selecting only the active coverage radio button but not yet the age
range radio enabled the continue. (You can try this on the dev deploy)
2) Switched from msp-personal-information cmpnt to the new
account-personal-information cmpnt
3) Fixed the 0-18 and 19-24 date range issue. It was just missing an
end range setting
Clicking between the 0-18 and 19-24 options no longer messes up date validation
> DEAM-338: Fix date range, radio button issues

- src/app/modules/msp-core/components/support-documents/support-documents.component.html
Small change, please review when convenient.
What I did:
Made `for` and `id` attrs unique. 
This is a change to msp-core but it is a very small change to a
component that is only used in DEAM so far. The unique attrs
mean clicking on an update label (like Correct Name) will 
focus its respective `<select>`, rather than all labels focusing
the first `<select>`
> DEAM-322: Fix dif. labels jumping to same select

- package.json
Changed `'0.0.0.0'` to `\"0.0.0.0\"` so that all OS can run the 
`dev` script. Previously didn't work on Windows
> DEAM-344: Edit package.json script for all OS

- src/app/modules/account/pages/child-info/remove-child/remove-child.component.html
- src/app/modules/account/pages/child-info/remove-child/remove-child.component.scss
- src/app/styles/overrides.scss
What I did:
1) Changed template structure of remove-child to match the remove-spouse
component, including adding the extra address line buttons
2) Styled the blue warning icon about children under 19
3) Add CSS fix to "Date no longer in full time studies" error issue (see
DEAM-330)
See attached for new version (old is on Jira ticket)
> DEAM-350: Cleanup remove-child, emulating spouse

- src/app/modules/msp-core/components/support-documents/support-documents.component.html
- src/app/modules/msp-core/components/support-documents/support-documents.component.ts
This is a bit of a verbose message but this component is used in
multiple places and it seems like it's an urgent feature, so I don't
want to miss anything
What I did:
1) Made use of errorDocument emitter in common-file-uploader
2) Replaced checkDuplicateDocs and newImage with supportDocError
(getter + setter), supportDocErrorMsg (getter + setter), and
handleSupportDocError.
3) Use enums to dictate which messages to dynamically show
Tried across IE, Chrome, etc. and in different combinations. The
remaining situations it doesn't handle well already exist in the
current version, and those is the following:
1) If you attempt to upload a filetype that isn't one of the expected
ones (.otf for example) it will show the error as expected, but
subsequent correct uploads will not run. For some …
> DEAM-351: Upload failure alerts

- src/app/modules/account/components/person-card/person-card.component.scss
- src/app/modules/account/pages/review/review.component.scss
- src/app/modules/msp-core/components/review-card/review-card.component.html
- src/app/modules/msp-core/components/review-card/review-card.component.scss
- src/app/styles/overrides.scss
There is some repetition here that should be removed later but I wanted
to touch as little as possible
See attached. You gotta look pretty closely at the pics to see the difference
Before:
After:
> DEAM-271: Line up icons in review page

- src/app/modules/account/components/moving-information/moving-information.component.html
This is the error in Openshift:
```
ERROR in src/app/modules/account/components/moving-information/moving-information.component.html(172,7): : Property 'setDeclarationForOutsideOver60Days' does not exist on type 'ChildMovingInformationComponent'.
```
> Attempt to fix master build issue.

- src/app/modules/account/components/moving-information/moving-information.component.html
- src/app/modules/account/models/base-form.ts
- src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
- src/app/modules/account/pages/spouse-info/spouse-info.component.ts
This is for the Spouse Info page.
What I did:
1) Changed validation from just being falsy or truthy to not undefined
and not null, for any odd cases where the value gets reset to null etc.
2) Added checks for arrays/objects before the length of content of them
was validated. Eg:
Instead of:
`if (some property of the object exists)`
I put:
`if (the object exists && some property of the object exists)`
3) Added validation for the "From (province or country)" field
4) Removed a comment in moving-information that is no longer needed
Could still use more validation
> DEAM-348: Make "From" field mandatory if visible

- src/app/modules/account/services/msp-api-account.service.ts
What I did:
1) Fix the validation for mailing addresses for children
2) Use the unknownAddress method to fill in missing info where 
appropriate
Attached is two payloads, one of them is a remove child and remove
spouse submitting with proper mailing address info, and the other is a
removed spouse with an unknown address being filled in properly
[address_payloads.zip](https://github.com/bcgov/MyGovBC-MSP/files/4936801/address_payloads.zip)
> DEAM-349: Get sp+ch mailingAddress info to payload

- src/app/modules/account/services/msp-api-account.service.ts
What I did:
1) Move willBeAway stuff out of populateBeneficiary methods and into
the main convert methods.
2) Changed the expression that got evaluated for the fullTimeStudent
property. Formerly it was just N if you were ever discharged. Now it's
if the relationship is 19-24 (has to be a fulltime student in that case)
JSON output for adding child and spouse both discharge attached:
[AddChildAddSpouseDischarge.zip](https://github.com/bcgov/MyGovBC-MSP/files/4936676/AddChildAddSpouseDischarge.zip)
> DEAM-363: Get spouse Can Forces info to payload

- src/app/modules/account/components/moving-information/moving-information.component.ts
What I did:
1) Import lodash and make a deep copy of the date object being used so
operations on the copy didn't affect the original
See attached screenshots and note the console in both. Birthdate was
being incremented every time discharge date was touched
>## Broken:
>## Fixed:
> DEAM-380: Fix discharge date affecting birthdate

- src/app/modules/account/pages/authorize/authorize.component.html
- src/app/modules/account/pages/authorize/authorize.component.scss
- src/app/modules/account/pages/authorize/authorize.component.ts
What:
1) Align the checkbox and label
2) Add a displayed error when they try to submit without it
3) Stop the submission from being sent without authorization
>### Before:
User clicks submit without checking the box or the captcha
User clicks submit with captcha but without checking the box (no longer happens)
>### After:
> DEAM-388: Fix errors on sending page

- src/app/modules/msp-core/components/moving-information/moving-information.component.spec.ts
It appears someone was using fdescribe to run tests they were working on
and committed it accidentally. The rest of the unit tests are working
now, and many of them need to be updated - see attached
>### Old:
>### New:
> DEAM-389: Enable remaining unit tests

- MSPApplicationSchema.json
- src/app/models/schema.ts
- src/app/modules/account/components/personal-information/personal-information.component.ts
- src/app/modules/account/pages/confirmation/confirmation.component.html
This is not yet ready to be merged, but please review when 
convenient
---
If AH adds a spouse or child and they don't have existing MSP
coverage, they should not be asked for a PHN. The front end
changes have been made in this PR (see attached below) as well
as changes to FE schema, but the middleware schema needs to 
be changed as well or submissions will fail. Middleware changes
are in-progress (Jing is working on it)
Once those changes have been made and I've tested 
submissions, I will convert this to a PR from a draft.
As an aside, the error page's "Next Steps" section looks like it
could use more content and not only (or maybe at all) refer to 
Enrolment (see attached below)
>### PHN not required if they don't have existing MSP:
---
>### Still required if they do have existing MSP: …
> DEAM-395: PHN not required for sp / ch

- src/app/modules/account/components/personal-information/personal-information.component.html
- src/app/modules/account/components/personal-information/personal-information.component.ts
As requested by Ernesto, the PHN field now still shows even when sp/ch
don't have existing MSP. It is now (in that case) optional, and the
new label indicates this. The previous change hid the field entirely.
AH info, spouse/child update and remove all unaffected. 
Submissions both with and without the optional PHN work
New Screenshots:
> DEAM-395: Still show non-mandatory PHN

- src/app/modules/account/components/moving-information/moving-information.component.html
- src/app/modules/account/pages/child-info/add-child/add-child.component.html
- src/app/modules/account/pages/child-info/child-info.component.ts
- src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
What I did:
1) Move add-child validation for residency info into if so it's only
checked if they don't have MSP
2) Bolden headers
3) Conditionally render residency info section
As an aside the child-moving-information cmpt should be broken up and
I think the spouse should use the hasActiveMedicalServicePlan like the
child does instead of immigrationStatusChange. I am not changing these 
right now due to the time pressure, but for maintainence it's worth noting
> DEAM-396: Remove residency info if child has MSP

- src/app/modules/request-acl/pages/acl-confirmation/acl-confirmation.component.spec.ts
- src/app/modules/request-acl/pages/request-letter/request-letter.component.spec.ts
- src/app/modules/request-acl/services/acl-api.service.spec.ts
- src/app/modules/request-acl/services/acl-data.service.spec.ts
- src/test.ts
Please review when convenient. To run these tests, swap the comment on the
`const context` lines in ./src/test.ts and run `ng test`
There was 4 tests failing out of 5, there should now be 11 passing (double with
karma browser)
> DEAM-400: Update unit tests in request-acl

- src/app/modules/account/pages/personal-info/personal-info.component.spec.ts
- src/app/modules/benefit/pages/confirmation/confirmation.component.spec.ts
- src/app/modules/benefit/pages/financial-info/prepare.component.spec.ts
- src/app/modules/enrolment/pages/address/address.component.spec.ts
- src/app/modules/enrolment/pages/personal-info/personal-info.component.spec.ts
- src/app/modules/enrolment/pages/prepare/prepare.component.spec.ts
- src/app/modules/enrolment/pages/review/review.component.spec.ts
- src/app/modules/request-acl/pages/acl-confirmation/acl-confirmation.component.spec.ts
- src/app/modules/request-acl/pages/acl-confirmation/acl-confirmation.component.ts
Please review when convenient. To test this PR, run `ng test`
There should be 166 passing tests, and the only logs that 
should show up now should be related to inactive routes 
and schema warnings or the xml ones (I don't know why
those logs exist but I don't want to touch them incase
they are needed for something)
> DEAM-404: Fix cleanup errors for various specs

- src/app/modules/account/pages/sending/sending.component.ts
Done to prevent re-submissions when they navigate back to /sending after
a successful submission. The previous behavior was if you successfully 
submit and then press back and go to /sending, it would attempt and
fail to submit, as the application data would now be empty. The new 
behavior is it redirects to the landing and reloads if you press back 
after a successful submission
Please check out this branch and review when convenient. I also advise
trying it with the environment set to `bypassGuards = false` to ensure
the same behavior will work when deployed
> DEAM-414: Prevent certain resubmissions

- src/app/modules/account/components/personal-information/personal-information.component.html
- src/app/modules/account/components/update-request/update-request.component.html
- src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
Was looking through Splunk, this issue caused 12 errors since release. We just needed to correct the input used
https://bcgov.github.io/moh-common-styles/components/NameComponent.html#maxlength
> DEAM-423: Fix max length inputs

- src/app/modules/msp-core/components/support-documents/support-documents.component.html
- src/app/modules/msp-core/components/support-documents/support-documents.component.ts
To test this branch, upload a bunch of large images, over ~1.3MB after
compression, in one support document slot (enough that you'd get a
failure on current test deploy.) On this branch you should see an error
message, and the slot should be cleared. Then upload docs that are
small/few enough that it allows you to continue and removes the error,
and ensure you have the correct number of docs in the review section.
Lastly, make sure the submission is successful.
>### If user tries to upload a duplicate
>### User can upload multiple attachments still
>### If user uploads more large attachments until the collective size is too high
> DEAM-420: Disable uploads with too high a size

- src/app/modules/account/models/account.dto.ts
- src/app/modules/account/models/account.model.ts
- src/app/modules/account/services/msp-account-data.service.ts
Hi Bryce,
I've update MSP Account Data Service to match with the Enrol Data Service. There are methods in MSP Account Data that have different names from Enrol Data Service but uses almost the same properties so I used those existing methods instead and modify the properties under them. Let me know if there are modifications that I missed or if there are anything that I should add/remove.
Thank you,
Cyril
> Modified MSP Account Data Service

- src/app/models/common-image-json.interface.ts
- src/app/models/common-image.dto.ts
- src/app/modules/enrolment/pages/authorize/authorize.component.ts
- src/app/modules/enrolment/services/enrol-data.service.ts
- src/app/modules/msp-core/models/support-documents.model.ts
- src/app/services/base-msp-data.service.ts
1) Applied DTO transfer to each image in support documents
2) New DTO and to/from methods for CommonImage type
3) Altered the support document DTO to use CommonImageDTO rather than
just CommonImage
4) Added hasNameChange check so the functions that follow are only be
called if necessary
5) Added `CommonImageJSON` interface to extend the common lib interface
`CommonAttachmentJson`
6) Fixed spelling of the console log that shows up when this error or others
like it occur
To test, check out this branch, navigate to enrolment, add an attachment, 
refresh, and continue on to submit. To see the original issue, do the same on
master
> DEAM-463: Fix enrolment bug (attachmentUuids)

- src/app/app.component.ts
Clearing the storage when someone refreshes on home is so that direct links to `/deam/home` (which is typically how DEAM is navigated to) will not be affected by the redirect, but the modal will still pop up if someone refreshes on that page after clicking through it
> DEAM-495: Handle refresh on DEAM

- package-lock.json
- package.json
- src/app/styles/overrides.scss
New MSP Version: 3.3.0
New moh-common-lib: 3.2.4
Removed a line of font-styling for the captcha that is no longer necessary since the update
> Update commmon lib and MSP version

- src/app/modules/account/pages/home/home.component.html
- src/app/modules/account/pages/home/home.component.scss
Hi,
I would like to ask for your quick code review. I've removed aside and changed it to div in order to the follow the header-main content-footer landmarks.
Here's the screenshot of the changes (Same style, just used div instead of aside):
Regards,
Cyril
> Remove aside tag on Home Page

- src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.html
- src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.ts
The cut off year was only assigned inside an `if` block that depended on it being assigned already. Cleaned things up as much as I could without touching code I didn't need to. This section of code hadn't been touched in over a year so it's possible it had different behavior in 2019
> DEAM-497: Fix conditional logic in suppben

- src/app/modules/account/pages/confirmation/confirmation.component.html
- src/app/modules/account/pages/home/home.component.html
- src/app/modules/assistance/pages/confirmation/confirmation.component.ts
- src/app/modules/benefit/pages/confirmation/confirmation.component.html
- src/app/modules/benefit/pages/eligibility/eligibility.component.html
- src/app/modules/enrolment/pages/confirmation/confirmation.component.html
- src/app/pages/landing/landing.component.html
Has no visible effect but for accessibility a main tag must always be present. On pages like `confirmation` that don't use their respective container components the main tags needed to be added in. This is all so navigation can be outside of main but main can still skip users to the content
> DEA11Y-39: Add missing main tags

- src/app/modules/account/pages/contact-info/contact-info.component.html
- src/app/modules/account/pages/contact-info/contact-info.component.scss
Removed the common-page-section as that was intended for the use of aside tags, and used regular bootstrap rows and columns to position it the same way. 
See here: https://bcgov.github.io/moh-common-styles/components/PageSectionComponent.html#template
(Closed and reopened to show less changes)
> DEA11Y-48: Remove asides in contact info

- src/app/modules/enrolment/models/enrol-form.ts
To test this branch, set `bypassGuards` to `false` and navigate through enrolment, refreshing 
on each page. It should not redirect as it used to on pages like spouse-info
> DEAM-503: Save application between pages

- src/app/modules/enrolment/pages/child-info/child-info.component.ts
- src/app/modules/enrolment/pages/personal-info/personal-info.component.ts
To see how this was causing issues, view the test repo and select the temporary permit option for account holder or child and fill out the `Moved from` field. You were able to continue when you hadn't filled out the rest of the fields
> DEAM-503: Fix temp worker validation

- src/app/modules/account/pages/child-info/child-info.component.ts
- src/app/modules/account/pages/spouse-info/spouse-info.component.html
- src/app/modules/account/pages/spouse-info/spouse-info.component.ts
Accessibility update, to adjust focus after button clicks. To test, click the add, update, and remove buttons for children and spouse, ensuring that the focus moves to the first input of each
> Add focusing to spouse and child button clicks
