bcgov/MyGovBC-MSP

README.md

Just reading through the markdown I caught a couple of spelling mistakes and grammar bits. Just a little tidy job.

Made grammar and spelling tweaks

---

src/app/components/msp/common/base/base.class.ts
src/app/components/msp/common/consent-modal/consent-modal.component.ts
src/app/components/msp/service/abstract-api.service.ts
src/app/components/msp/service/msp-api.service.ts
src/app/components/msp/service/msp-maintenance.service.ts

Removed promise and updated the code with the Abstract API and observables.

Updated the code with the Observable

---

src/app/components/msp/service/msp-maintenance.service.ts

Updated the log service in the error handler

Updated the log service in the error handler

---

src/app/components/msp/account/add-dependents/add-dependents.component.html
src/app/components/msp/common/name/name.component.ts
src/app/components/msp/common/phn/phn.component.ts
src/app/components/msp/common/phone/phone.component.ts

The fix address a bug with Angular 6 where the last character is not saved to session storage

Angular6 bug 

---

src/app/components/msp/common/person-card/person-card.component.html
src/app/components/msp/common/person-card/person-card.component.ts
src/app/components/msp/service/msp-data.service.ts
src/app/models/msp-constants.ts
src/app/modules/enrolment/enrol-page-routing.module.ts
src/app/modules/enrolment/pages/address/address.component.html
src/app/modules/enrolment/pages/address/address.component.ts
src/app/modules/enrolment/pages/authorize/authorize.component.html
src/app/modules/enrolment/pages/child-info/child-info.component.html
src/app/modules/enrolment/pages/confirmation/confirmation.component.html
src/app/modules/enrolment/pages/confirmation/confirmation.component.ts
src/app/modules/enrolment/pages/personal-info/personal-info.component.html
src/app/modules/enrolment/pages/review/review.component.html
src/app/modules/enrolment/pages/sending/sending.component.html
src/app/modules/enrolment/pages/sending/sending.component.ts
src/app/modules/enrolment/pages/spouse-info/spouse-info.component.html
src/app/modules/msp-core/components/personal-details/personal-details.component.html

- Updated the common-page-framework in all the pages
- Updated the new design for Authorize, Confirmation and Personal info
- Added the remove spouse and remove child buttons
- Updated the new link

New design updates to the Authorize, confirmation and personal info page

---

src/app/modules/benefit/benefit-page-routing.modules.ts
src/app/modules/benefit/benefit-routing.module.ts
src/app/modules/benefit/benefit.module.ts
src/app/modules/benefit/components/benefit-container/benefit-container.component.ts
src/app/modules/benefit/models/benefit-application.model.ts
src/app/modules/benefit/pages/address/address.component.ts
src/app/modules/benefit/pages/authorize-submit/authorize-submit.component.ts
src/app/modules/benefit/pages/personal-info/personal-detail/i18n/data/en/index.js
src/app/modules/benefit/pages/personal-info/personal-detail/personal-detail.component.html
src/app/modules/benefit/pages/personal-info/personal-detail/personal-detail.component.ts
src/app/modules/benefit/pages/personal-info/personal-info.component.ts
src/app/modules/benefit/pages/prepare/prepare.component.html
src/app/modules/benefit/pages/prepare/prepare.component.ts
src/app/modules/benefit/pages/review/review.component.ts
src/app/modules/benefit/pages/sending/sending.component.ts
src/app/modules/benefit/pages/spouse-info/spouse-info.component.ts
src/app/modules/msp-core/components/common-deduction-calculator/common-deduction-calculator.component.ts

- Activate the router guards.
- Removed the Sending tab.
- Arranged the routes.
- Separated the file uploader for Applicant and spouse.
- Fixed the address issue 
- Updated the code the make the Attachment API call for spouse, applicant, and application

Updated and fixed issues with Supplementary benefits

---

package.json
src/app/modules/benefit/benefit-page-routing.modules.ts
src/app/modules/benefit/benefit.component.txt
src/app/modules/benefit/benefit.module.ts
src/app/modules/benefit/models/benefit-application.model.ts
src/app/modules/benefit/pages/authorize-submit/authorize-submit.component.ts
src/app/modules/benefit/pages/prepare/tax-year/tax-year.component.html
src/app/modules/benefit/pages/prepare/tax-year/tax-year.component.ts
src/app/pages/landing/landing.component.html
src/app/pages/landing/landing.component.ts

- Updated the first tab to Financial info tab
- Fixed the radio animation on prepare page
- Have updated the application to not required Spouse consent on Authorization (Excel sheet feedback by the business)

Fixed CSS animation on prepare, Renamed prpare to financial info

---

src/app/modules/assistance/pages/authorize-submit/authorize-submit.component.ts
src/app/modules/assistance/pages/contact/assist-contact.component.ts
src/app/modules/assistance/pages/home/home.component.ts
src/app/modules/assistance/pages/personal-info/personal-info.component.ts
src/app/modules/assistance/pages/spouse/spouse.component.ts
src/app/modules/msp-core/components/birthdate/birthdate.component.ts

Fixed bug issues: MSPRSP 154, 157 and 158

First batch of bug fix for Retro PA

---

package.json
src/app/modules/assistance/assistance-routing.module.ts
src/app/modules/assistance/components/assist-container/assist-container.component.ts
src/app/modules/assistance/components/assist-cra-documents/assist-cra-documents.component.ts
src/app/modules/assistance/guards/assist.guard.ts
src/app/modules/assistance/pages/authorize-submit/authorize-submit.component.ts
src/app/modules/assistance/pages/confirmation/confirmation.component.ts
src/app/modules/assistance/pages/contact/assist-contact.component.ts
src/app/modules/assistance/pages/home/home.component.ts
src/app/modules/assistance/pages/personal-info/personal-info.component.ts
src/app/modules/assistance/pages/review/review.component.ts
src/app/modules/assistance/pages/spouse/spouse.component.ts
src/app/modules/assistance/services/assist-state.service.ts
src/app/modules/assistance/services/assist-transform.service.ts
src/app/modules/benefit/services/api-send.service.ts
src/environments/environment.ts
src/version.GENERATED.ts

Route guards working, colors fixed on buttons, fix for Kevin's pdf
Please merge

Pa bug fixes

---

src/app/modules/request-acl/pages/acl-confirmation/acl-confirmation.component.html
src/app/modules/request-acl/pages/request-letter/request-letter.component.ts

Error message mimics message on old app.

Message fix acl

---

src/app/modules/assistance/models/financial-assist-application.model.ts
src/app/modules/assistance/pages/home/home.component.ts
src/app/modules/assistance/pages/spouse/spouse.component.html
src/environments/environment.ts
src/version.GENERATED.ts

Fix for retro pa year - should not go pass taxyear 2018

---

package-lock.json
package.json
src/app/modules/msp-core/components/moving-information/moving-information.component.html
src/app/modules/msp-core/components/moving-information/moving-information.component.ts
src/version.GENERATED.ts

Date fix and updated common library version that contains splash page/date fixes too.

Msp issues

---

src/app/modules/account/pages/home/home.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/request-acl/pages/request-letter/request-letter.component.html

Hi @jhamidi ,
I would like to request for your review regarding DEAM-53 (CR 19009). Thank you.
Regards,
Cyril

Fixed missing 's' in Medical Services Plan

---

src/app/modules/account/pages/home/home.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/msp-core/components/review-card/review-card.component.scss
src/app/modules/request-acl/pages/request-letter/request-letter.component.html

Hi @jhamidi ,
Regarding DEAM-54 (CR 19010), not 100% sure if the fix that I made in this PR is the one that has the font issue. Let me know if it's correct or if I need to make more changes. Thank you.
Regards,
Cyril

Fixed font issue on the Review Page for the "Edit" word

---

package-lock.json
package.json

https://github.com/chialab/schema-model

Added the SchemaModel <@chialab/schema-model> npm module.

---

src/app/modules/account/pages/home/home.component.html

Hi @jhamidi / @samuel-amos
I would like to ask for your code review before I merge these changes to msp-deam. Thank you.
Regards,
Cyril

MSP Deam Changes for DEAM-57 and 58

---

openshift/local-nginx/Dockerfile
openshift/templates/nginx-runtime/Dockerfile

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

Fix file and folder permissions on nginx-runtime

---

src/app/modules/account/pages/home/home.component.html
src/app/modules/account/pages/home/home.component.scss

Hi Jam/Samuel,
Please check my minor modifications in the landing page before I merge it.
Regards,
Cyril

Modified landing page based from the updated wireframe

---

src/app/modules/account/pages/home/home.component.html
src/app/modules/account/pages/home/home.component.scss

Good morning @jhamidi / @samuel-amos 
I would like to request your review and approval for my branch. This PR includes:
- Button layout changes in the Home Page
- Font change similar to the Wireframe
- Screen responsive to different screen sizes
- Button with external links opens a new tab
- Minor text changes for the "Address Change Only"
Thank you.
Regards,
Cyril

Fixed layout issue with MSP Deam Home Page

---

src/app/components/msp/model/msp-person.dto.ts
src/app/components/msp/model/msp-person.model.ts
src/app/models/schema.ts
src/app/modules/account/components/personal-details/personal-details.component.html
src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/account/pages/contact-info/contact-info.component.html
src/app/modules/account/pages/contact-info/contact-info.component.ts
src/app/modules/account/pages/personal-info/personal-info.component.html
src/app/modules/account/pages/sending/sending.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts
src/app/modules/account/services/msp-account-data.service.ts
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/enrolment/pages/personal-info/personal-info.component.html
src/app/modules/msp-core/components/full-name/full-name.component.html
src/app/modules/msp-core/components/personal-information/personal-information.component.html
src/app/modules/msp-core/components/support-documents/support-documents.component.html
src/app/modules/msp-core/components/support-documents/support-documents.component.ts
src/app/modules/msp-core/models/canadian-status.enum.ts
src/app/modules/msp-core/models/support-documents.enum.ts

Good morning @jhamidi / @samuel-amos 
Please review my changes in Contact Info Page. This PR includes:
- Adding "Allow Extra Lines" for the Street Address field
- Setting Province and Country in Residential Address as Read-Only
- Page responsive for the Phone Number field
- Fixed navigation link to Review Page when "Continue" Button is clicked
- Minor text changes below the Contact Info header
Thank you,
Cyril

Changes on MSP Deam Contact Info Page (WIP)

---

src/app/modules/account/models/account.model.ts
src/app/modules/account/pages/review/i18n/data/en/index.js
src/app/modules/account/pages/review/review.component.html
src/app/modules/account/pages/review/review.component.ts
src/app/modules/msp-core/components/person-card/i18n/data/en/index.js
src/app/modules/msp-core/components/person-card/person-card.component.html

Hi Jam/Samuel,
I would like to ask for your review and approval before we merge this branch to 'msp-deam'.
This PR includes:
- Adding the updates requested by the Account Holder in the Account Holder Info from the Personal Info Page
- Adding "Add/Update/Remove Spouse Information" in the Review Page
- Adding "Add/Update/Remove Child Information" in the Review Page
- Adding "Contact Information" in the Review Page
Thank you,
Cyril

Changes for MSP DEAM Review Page

---

src/app/modules/account/pages/review/review.component.html
src/app/modules/account/pages/review/review.component.ts
src/app/services/process.service.ts

Hi Jam/Samuel,
I've updated my branch to fix the the failed build issue. This PR includes:
- Modifying the router links from the Review Page
- Updating the router link from '/account/' to '/deam/...'
- Adding a Contact Info URL in the 'ProcessUrls'
I would like to ask for your review before merging it to 'msp-deam' branch.
Thank you,
Cyril

Fixed router links for MSP DEAM Review Page

---

src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/account/pages/confirmation/confirmation.component.scss
src/app/modules/account/pages/confirmation/confirmation.component.ts

Hi Jam/Samuel,
I would like to ask your quick review for this before merging this branch to msp-deam.
Regards,
Cyril

Finalized Confirmation Page - added info alert

---

src/app/modules/assistance/components/assist-cra-documents/assist-cra-documents.component.ts
src/app/modules/assistance/pages/contact/assist-contact.component.ts

See: https://devtools.maximusbc.ca/jira/browse/DEF-171

Change text to accommodate changes from wire frame

---

src/app/modules/account/pages/personal-info/account-file-uploader/account-file-uploader.component.html
src/app/modules/assistance/components/assist-cra-documents/assist-cra-documents.component.ts
src/app/modules/assistance/pages/contact/assist-contact.component.ts
src/app/modules/benefit/components/personal-details-retro-suppben/personal-details-retro-suppben.component.html
src/app/modules/benefit/components/personal-details-retro-suppben/personal-details-retro-suppben.component.ts
src/app/modules/benefit/pages/contact-info/address.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.html

See: https://devtools.maximusbc.ca/jira/browse/DEF-172
This also adds proper usage of Relationship enum in `personal-details-retro-suppben.component.{html/ts}`; it was previously using integer comparisons.

Add text changes according to wireframe.

---

MSPApplicationSchema.json
package-lock.json
package.json
src/app/constants.ts
src/app/models/schema.ts
src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/benefit/models/benefit-application.dto.ts
src/app/modules/benefit/models/benefit-application.model.ts
src/app/modules/benefit/pages/financial-info/eligibility-card/eligibility-card.component.ts
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.ts
src/app/modules/benefit/pages/personal-info/personal-info.component.html
src/app/modules/benefit/pages/personal-info/personal-info.component.ts
src/app/modules/benefit/services/msp-api-benefit.service.ts
src/app/modules/benefit/services/msp-benefit-data.service.ts
src/app/modules/msp-core/components/common-deduction-calculator/common-deduction-calculator.component.ts
src/app/modules/msp-core/interfaces/i-api.ts

This adds the new behaviour required by [DEF-173](https://devtools.maximusbc.ca/jira/browse/DEF-173).
Some adjustments were made to how this data is managed by the form and component, then expanded upon to reliably collect and send the correct data. Some edge cases were tested for (i.e. what happens if you modify spouse information/child count after attendant care values are set) which caught some bugs, but I'm sure there are more cases to test for.
I've added a constants file with only one constant in it. I've done this because I found a lot of repeated 'magic numbers' such as the attendant care claim amount, and I think it would be a good idea to move values like that into the constants file in the future.
The architecture of this Angular app is a bit different than I'm used to, but …

Handle {applicant,spouse,child}AttendantCareExpense data

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts
src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/child-info/child-info.component.scss
src/app/modules/account/pages/home/home.component.html
src/app/modules/account/pages/personal-info/personal-info.component.html
src/app/modules/account/pages/personal-info/personal-info.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.scss
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/msp-core/components/person-card/person-card.component.ts

Added CSS class.
Linting.
Removal of blocks of commented code.

Small updates.

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/child-info/remove-child/remove-child.component.html
src/app/modules/account/pages/child-info/update-child/update-child.component.html

Child Info Page Update

---

src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/contact-info/contact-info.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.html

Minor update with the color of the "My mailing address is different" button. DEAM-97 is now fully complete.

Minor update in changing the color of the button

---

src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.scss
src/app/modules/account/pages/spouse-info/spouse-info.component.html

Moved the bottom Add/Remove/Update inside an if clause.

---

src/app/styles/overrides.scss

https://devtools.maximusbc.ca/jira/browse/DEAM-104

DEAM-104: Increase checkbox size.

---

src/app/modules/account/pages/authorize/authorize.component.html
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/account/pages/contact-info/contact-info.component.html
src/app/modules/account/pages/personal-info/personal-info.component.html
src/app/modules/account/pages/review/review.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.html
src/app/styles/overrides.scss

Hi Sam/Harry,
I would like to ask for a code review before I merge it to msp-deam branch. This PR contains:
- Modification of white space on each side for every DEAM page (fixing the horizontal scrolling issue)
- Modification of the font weight for Review and Confirmation page
Thank you,
Cyril

Added white space on both sides for every DEAM page

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/personal-details/personal-details.component.ts
src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/contact-info/contact-info.component.ts
src/app/modules/account/pages/personal-info/personal-info.component.html
src/app/modules/account/pages/personal-info/personal-info.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.scss
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/benefit/pages/eligibility/eligibility.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.html
src/app/modules/msp-core/components/personal-information/personal-information.component.html
src/app/modules/msp-core/models/support-documents.enum.ts
src/app/modules/request-acl/pages/request-letter/request-letter.component.html

The state of Add and or Remove is remembered on page refresh.
Linting.

Spouse Info: Add/Remove can be done at the same time.

---

src/app/modules/account/pages/review/review.component.html
src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/msp-core/api-model/accountChangeTypes.ts
src/app/modules/msp-core/components/person-card/person-card.component.html
src/app/services/msp-api.service.ts

Hi,
Sorry, I just realized I should have create a new branch for this earlier. This PR has the fix re: the payload bug when the user adds a spouse.
Regards,
Cyril

Json payload

---

src/app/components/msp/model/msp-person.model.ts
src/app/modules/account/models/account.model.ts
src/app/modules/account/services/api-send.service.ts
src/app/modules/account/services/msp-api-account.service.ts

Note: this causes an error upon form submit:
```
{
"op_return_code" : "FAILURE",
"op_technical_error" : null,
"dbErrorMessage" : "Validation error on Application UUID = 439b09f6-9f82-37c4-59c7-ba244018111b",
"op_reference_number" : null,
"req_num" : "439b09f6-9f82-37c4-59c7-ba244018111b"
}
```
Unknown as to why.

Add attachments to JSON payload.

---

MSPApplicationSchema.json
src/app/models/schema.ts
src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/msp-core/api-model/accountChangeTypes.ts
src/app/modules/msp-core/interfaces/i-api.ts
src/app/services/msp-api.service.ts

Hi,
I'm able to add Account Holder and Spouse but for some reason, Child is not adding to the JSON payload. I would like to request for a code review for this and let me know if I need to modifications with the code.
Thank you,
Cyril

WIP: Adding Account Holder, Spouse and Child in JSON Payload

---

src/app/modules/account/services/msp-api-account.service.ts

Hi,
I would like to ask for your code review for this PR.  I've fixed the payload for the child in this PR and verified that it's going through.
Thank you and Regards,
Cyril

Json payload for Child

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/msp-core/components/canadian-status/canadian-status.component.ts

Updated the display logic of the Child Info page.

---

src/app/modules/account/pages/sending/sending.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html

When Yes is selected the form from the wireframe is now displayed.
Linted.

The "Has your spouse's name changed due to marriage?"

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.html

Resolves the following tickets:
https://devtools.maximusbc.ca/jira/browse/DEAM-139
https://devtools.maximusbc.ca/jira/browse/DEAM-141

Comm updates.

---

src/app/modules/account/pages/child-info/child-info.component.html

Resolves the following issue:
https://devtools.maximusbc.ca/jira/browse/DEAM-142

Bulleted list in child info page.

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html

The question isn't included in the wire-frames, so I removed it.

DEAM-121: Removed adoption question.

---

src/app/modules/msp-core/components/person-card/i18n/data/en/index.js
src/app/modules/msp-core/components/person-card/person-card.component.html
src/app/modules/msp-core/components/person-card/person-card.component.ts

Hi,
I would like to ask for a code review for the changes on Personal Info for the Review Page.
Thank you,
Cyril

Fixed Status in Canada label for Personal Info

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts

Hi,
I would like to ask for your code review. Thank you.
Regards,
Cyril

DEAM 158 - Fixed discharge date issue

---

src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html
src/app/modules/account/services/msp-api-account.service.ts
src/app/styles/overrides.scss
src/app/styles/variables.scss

Hi everyone,
I would like to request a code review before I merge it to msp-deam branch. Re the size of the "Street" field, I've added "allowExtraLines" property instead to fix the field size issue. If you have better solution, let me know. For the background color issue, It looks the same to me although Ernesto said that the bg color of the fields are different. Can you guys take a quick look at this issue? -https://devtools.maximusbc.ca/jira/browse/DEAM-161
Thank you,
Cyril

Remove Spouse - UI Issue with fields and background color

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts
src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/child-info/update-child/update-child.component.ts
src/app/modules/account/pages/personal-info/personal-info.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/account/pages/spouse-info/update-spouse/update-spouse.component.ts
src/app/modules/enrolment/pages/child-info/child-info.component.html
src/app/modules/msp-core/components/canadian-status/canadian-status.component.html
src/app/modules/msp-core/components/canadian-status/canadian-status.component.ts
src/app/modules/msp-core/components/moving-information/moving-information.component.html
src/version.js

Created show methods to take into consideration the different combination of status and reasons.
Updated the styling for the spouse page.

Deam 106: Spouse Info Page: Status Change Reasons

---

src/app/modules/account/services/msp-api-account.service.ts

Temporarily adding back `gender` field to make submissions work in Test environment.

Add back default `gender` value.

---

src/app/modules/account/account.component.txt
src/app/modules/account/components/moving-information/moving-information.component.ts
src/app/modules/account/models/ProgressBarHelper.ts
src/app/modules/account/models/account-response.interface.ts
src/app/modules/account/models/account.dto.ts
src/app/modules/account/models/account.model.ts
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/account/pages/confirmation/confirmation.component.ts
src/app/modules/account/pages/personal-info/personal-info.component.ts
src/app/modules/account/pages/review/review.component.html
src/app/modules/account/pages/sending/sending.component.html

Updated the child validation.
Linted files that were touched.

Deam 83 - Updated the validation for continuing to the Contact Info page

---

src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/msp-core/components/person-card/person-card.component.html

Hi,
I would like to ask for your code review.
Thank you.

DEAM-190 Cyril

---

src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/account/components/update-request/update-request.component.ts

'Update name - due to marriage' removed from Child Info page

---

src/app/modules/account/pages/spouse-info/spouse-info.component.ts

Fixed a bug related to updating a spouses name due to marriage.

---

src/app/modules/account/pages/personal-info/personal-info.component.html
src/app/modules/account/pages/spouse-info/update-spouse/update-spouse.component.ts

Please review the updates for this ticket.

DEAM-244: Added 'the' to the 'What updates are you requesting for `the` Account Holder?'

---

src/app/modules/account/pages/contact-info/contact-info.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/msp-core/components/moving-information/moving-information.component.ts

In certain circumstances when update name due to marriage is selected a console error is thrown.
Please review this ticket.

DEAM-253: Console error no longer thrown.

---

src/app/modules/account/models/account.model.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html

Linted.
Please review this PR.

DEAM-233: Updated the add spouse test to match the wire-frame.

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts

DEAM-246: Marriage date can not be before Birthdate.

---

src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/msp-core/components/address-card-part/address-card-part.component.html

DEAM-254: No longer returns a console error related .length.

---

src/app/modules/account/pages/spouse-info/spouse-info.component.ts

DEAM-257: Continue inactive when current mailing address is not selected

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts
src/app/modules/account/pages/child-info/child-info.component.ts

Health # in previous place of residence is no longer required

---

src/app/styles/additions.scss

DEAM-285: Fix gap below footer

---

src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

The error is DoB > Marriage Date functions properly.

---

src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/account/pages/child-info/add-child/add-child.component.ts
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/child-info/update-child/update-child.component.html
src/app/modules/account/pages/child-info/update-child/update-child.component.scss
src/app/modules/account/pages/child-info/update-child/update-child.component.ts
src/app/modules/msp-core/components/canadian-status/canadian-status.component.ts
src/app/modules/msp-core/components/support-documents/support-documents.component.ts

Linting
Please review this PR.

Child update check boxes not match the wire-frame.

---

src/app/modules/account/pages/child-info/child-info.component.ts

Added the  missing DocList in child-info.component.ts

---

src/styles.scss

Checked across Chrome, Edge, Firefox. See attached
Previous:
Now:

DEAM-276: Fix cut off text in select options

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/add-child/add-child.component.ts
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/child-info/remove-child/remove-child.component.html
src/app/modules/account/pages/child-info/remove-child/remove-child.component.ts
src/app/modules/account/pages/child-info/update-child/update-child.component.html
src/app/modules/account/pages/child-info/update-child/update-child.component.ts
src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.ts
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.ts
src/app/modules/account/pages/spouse-info/update-spouse/update-spouse.component.ts

What I did:
1) Moved PHN list creation from spouse add/update/remove to spouse
info
2) Passed the PHN list into add/update/remove
3) Added a getter in add/update/remove to filter out current PHN from
list of duplicates
4) Did the same for child

DEAM-287: Prevent duplicate PHNs (unlinted)

---

README.md

Yarn is no longer used for install

DEAM-293: Fix README setup instructions

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/account/components/update-request/update-request.component.scss
src/app/modules/account/components/update-request/update-request.component.ts

Updated the CSS classes to ensure the Document type and file up-loader width to be consistent

DEAM-306: Inconsistent document type and file uploader

---

src/app/modules/msp-core/models/canadian-status.enum.ts

DEAM-326: 'Visiting' -> 'Visitor Permit'

---

src/app/styles/overrides.scss

Specifically the radio for name change due to marriage in add spouse. The JIRA ticket for this one is very vague, but a similar ticket (DEAM-180) has a good explanation. 
Tiny fix, please review when convenient

DEAM-314: Ensure radio only needs to be clicked once

---

src/app/modules/account/pages/child-info/child-info.component.ts

Was just checking addedChildren, now checking addedChildren.length > 0

DEAM-291: Tweak upd, rem, add checks

---

src/app/modules/account/pages/contact-info/contact-info.component.html

Small fix, please review when convenient

DEAM-332: Fix checkbox overlap on IE

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.ts

What I did:
1) Added missing required attributes
2) Removed duplicate names on different radio buttons that negated the required attr

DEAM-328: Prevent incomplete form active continue

---

src/app/modules/account/pages/personal-info/personal-info.component.ts

selectedPersonalInfoChange displays properly in the JSON payload

---

src/app/modules/account/pages/child-info/child-info.component.ts

What I did:
1) Make date and/or mailing address radio button mandatory for appropriate cancellation
options

DEAM-342: Make some remove-child options mandatory

---

src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html
src/app/styles/overrides.scss

Please review this minor change when convenient
What I did:
1) Moved the existing fix (DEAM-314, 180) onto the other remaining common-date slots
2) Fixed a spelling error
For now I just reused the existing fix. But the way it is, if at some 
point in the future someone decides to change the height of the 
error container, it will go back to the old behavior. If it's possible to 
alter the moh-common-styles repo, I think it should be changed 
there eventually

DEAM-330: Ensure radio buttons need only one click

---

src/app/modules/account/pages/home/home.component.html
src/app/modules/account/pages/home/home.component.scss

DEAM-357: Adjust alert icon on home page

---

src/app/modules/account/pages/child-info/child-info.component.ts

What I did:
1) Added validation to make sure radio was checked, if checked added
validation to make sure date and institution name was mandatory too.
2) Did the same with newly adopted while I was here

DEAM-355: Make discharge radio and info mandatory

---

src/app/modules/account/components/moving-information/moving-information.component.ts

@cyrilbravo I had to add back this method in order for the builds to work. It got broken in this PR: https://github.com/bcgov/MyGovBC-MSP/pull/444
Let me know if you have any issue with this. Thanks.

DEAM-335: Fixed removed method.

---

src/app/modules/account/pages/child-info/update-child/update-child.component.ts
src/app/modules/msp-core/components/support-documents/support-documents.component.ts

DEAM-341: Add to and correct name change docs

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts

DEAM-327: Add validation for school dates

---

src/app/modules/account/pages/personal-info/personal-info.component.ts
src/app/modules/account/services/msp-api-account.service.ts

Also addresses DEAM-303
[payload.zip](https://github.com/bcgov/MyGovBC-MSP/files/4935235/payload.zip)

DEAM-318: Ensure selectedX values populating

---

src/app/modules/account/models/base-form.ts
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/add-child/add-child.component.ts
src/app/modules/account/pages/child-info/child-info.component.ts

Please review when convenient, probably easiest to pull the branch and
try it out.
What I did:
1) Add validation to child info, following spouse info pattern
2) Removed unused method from add-child
3) Make strict equals in add-child conditional rendering
Also addresses DEAM-356

DEAM-364: Thorough add child validation

---

src/app/modules/account/models/base-form.ts
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/child-info/remove-child/remove-child.component.html
src/app/modules/account/pages/child-info/remove-child/remove-child.component.ts

Please review when convenient.
What I did:
1) Added date ranges and errors to cancellation dates
2) Added more validation, now you can't proceed if the option
you choose is "Out of Province / Country"

DEAM-366: Thorough remove child validation

---

src/app/modules/account/models/base-form.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

Small changes, please review when convenient

DEAM-365: Thorough remove spouse validation

---

src/app/modules/account/models/base-form.ts
src/app/modules/account/pages/child-info/child-info.component.ts

What I did:
1) Added successive validation for additional docs fields, so the radio
buttons that are a level down are still mandatory when visible
2) You can no longer pass this page without making an update

DEAM-367: Thorough update-child validation

---

src/app/modules/account/models/base-form.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

More validations, this time update spouse. Please review when convenient
What I did:
1) Can no longer proceed without selecting at least one update
2) Made all visible radio buttons mandatory
3) Added safer checks (ie. instead of just checking images.length
check images exists in the first place)

DEAM-368: Thorough update spouse validation

---

src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/msp-core/models/support-documents.enum.ts

What I did:
1) "Legal Name Change Certificate" -> "Name Change Certificate /
Certificate of Name Change"
2) Change support document list used in update-request to correct one
In response to Ernesto's feedback from last test run
Screenshots:

DEAM-341: Change title of support document

---

src/app/modules/account/components/person-card/person-card.component.html
src/app/modules/account/components/person-card/person-card.component.ts

DEAM-370: Edit review page content
This was an update requested by Ernesto. Please review when convenient
What I did:
1) Put PHN before Status In Canada and moved document count to the
bottom of the card (as per mockups). Moved school
address next to rest of school info
2) Removed 12 and 6 month dates, reasons, locations. Left only the yes
or no value (Ernesto asked for this)
3) Added mailing address for removed spouses and children, put it at the
bottom of the cards (Ernesto asked for this)
4) Fixed hasDocumentAttached and documentCount to include spouse and
children files by changing the check to be for documents
themselves rather than the fields associated with documents. This
is because children and spouses don't have all the same fields as the
AH so the documents themselves are the …

DEAM-370: Edit review page content

---

src/app/modules/account/pages/personal-info/personal-info.component.ts

DEAM-373: Mandatory radio for additional gen docs

---

src/app/models/status-activities-documents.ts
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.html
src/app/modules/account/pages/spouse-info/remove-spouse/remove-spouse.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

Hi,
I would like to ask for your code review. Below are the screenshots of the fix:
If cancellation date is before birthdate
If cancellation date is the birthdate
If cancellation date is between the birthdate and currentdate (not during the current month)
If cancellation date is during the current month of the current date
If cancellation date is beyond the current date
Please review the screenshots if it's good to go. Thank you.

Deam 343 cyril

---

src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/account/pages/confirmation/confirmation.component.ts

I'm not sure I reproduced the exact same issue, but I've taken screenshots before and after forcing a failed status code. See attached. If the response is not success, the blurb about reference numbers no longer shows.
>## Forced Error:
>## Successful submission:

DEAM-377: Confirmation message issue

---

src/app/modules/account/components/moving-information/moving-information.component.html

Please review when you have 0.5 seconds
Limit was too long, needed to be 25
>## Limit

DEAM-382: Limit 'From' field to 25 char

---

src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

DEAM-384: Disable continue on non-perm move

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts
src/app/modules/account/pages/spouse-info/spouse-info.component.ts

Please review when convenient. Try it out on your local, zoom me if you
want a walkthrough
What I did:
1) Added getters for dynamic ranges, dynamic error messages. and cleaner 
person property access
2) Ordered methods and properties of moving-information and grouped them
3) Made small piece of spouse info logic more readable
It's still not perfect but it's a lot better than it was

DEAM-381: Date validation for moving information

---

src/app/modules/account/components/moving-information/moving-information.component.ts

This minor change only affects DEAM, not enrollment

DEAM-393: Allow future discharge dates

---

src/app/modules/account/components/personal-details/i18n/data/en/index.js
src/app/modules/account/components/update-request/update-request.component.ts
src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/child-info/child-info.component.ts
src/app/modules/account/pages/child-info/remove-child/remove-child.component.html
src/app/modules/account/pages/child-info/update-child/update-child.component.html

DEAM-392: updated to ensure every instance of "child" is "the child".

---

src/app/modules/account/pages/spouse-info/add-spouse/add-spouse.component.html

DEAM-391: Added "spouse's" to Update name - due to marriage or divorce

---

src/app/modules/benefit/benefit.module.spec.ts
src/app/modules/benefit/components/benefit-container/benefit-container.component.spec.ts
src/app/modules/benefit/components/personal-details-retro-suppben/personal-details-retro-suppben.component.spec.ts
src/app/modules/benefit/pages/authorize-submit/authorize-submit.component.spec.ts
src/app/modules/benefit/pages/confirmation/confirmation.component.spec.ts
src/app/modules/benefit/pages/contact-info/address.component.spec.ts
src/app/modules/benefit/pages/eligibility/eligibility.component.spec.ts
src/app/modules/benefit/pages/financial-info/eligibility-card/eligibility-card.component.spec.ts
src/app/modules/benefit/pages/financial-info/prepare.component.spec.ts
src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.spec.ts
src/app/modules/benefit/pages/personal-info/personal-info.component.spec.ts
src/app/modules/benefit/pages/review/review.component.spec.ts
src/app/modules/benefit/pages/sending/sending.component.spec.ts
src/app/modules/benefit/pages/spouse-info/spouse-info.component.spec.ts
src/app/modules/benefit/services/msp-api-benefit.service.spec.ts
src/app/modules/benefit/services/msp-benefit-data.service.spec.ts
src/test.ts

Please review when convenient. To run these tests, swap the comment on 
the `const context` lines in ./src/test.ts and then run `ng test`
There was 15 failing tests, there should now be 57 passing (double with
karma browser)

DEAM-402: Fix unit tests for benefit spec

---

src/app/modules/account/pages/sending/sending.component.ts

Change URL for deployment, add extra check to make sure resubmission doesn't happen

DEAM-414: Change URL for deployed version

---

package.json

Updated the application version from v3.2.0 to v3.2.2

---

src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/benefit/services/msp-api-benefit.service.ts
src/app/services/base-msp-api.service.ts
src/app/services/msp-api.service.ts

This pull request is to correct an update I accidentally committed directly to master.

Updated the error logs for attachments that failed to be processed.

---

src/app/modules/account/services/msp-api-account.service.ts
src/app/modules/benefit/services/msp-api-benefit.service.ts
src/app/modules/enrolment/services/msp-api-enrolment.service.ts

Fixed the spelling of becuase.

---

e2e/enrolment/src/mspe-spouse-info.e2e-spec.ts
src/app/modules/account/pages/child-info/child-info.component.html
src/app/modules/account/pages/spouse-info/spouse-info.component.html

Please review this button text update.

DEAM-430: Replaced 'No Spouse' and 'No Child' with 'Skip'.

---

package-lock.json
src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/enrolment/pages/confirmation/confirmation.component.html

Updated the text snippets to be in line with the changes being made to BCSC-related content
>### Before and After of Account Confirmation
>### Before and After of Enrolment Confirmation

DEAM-426: ICBC Content Update

---

src/app/pages/landing/landing.component.html

Deam 431: Remove Continue Application buttons (option B)

---

package-lock.json
src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/enrolment/pages/confirmation/confirmation.component.html

Reverts bcgov/MyGovBC-MSP#543
Was premature, as we don't yet have approval for this text change

Revert "DEAM-426: ICBC Content Update"

---

src/app/modules/enrolment/pages/child-info/child-info.component.html
src/app/modules/enrolment/pages/child-info/child-info.component.ts

To test this branch:
1. Check out master
2. Work through an enrolment application until you get to Child Info
3. Fill out all fields
4. Remove your uploaded Canadian status document
5. Click continue
6. Check out this branch
7. Repeat steps 2-5

DEAM-463: Fix continue without attachment bug

---

src/app/modules/enrolment/pages/child-info/child-info.component.ts
src/app/modules/enrolment/pages/personal-info/personal-info.component.ts
src/app/modules/enrolment/pages/spouse-info/spouse-info.component.ts
src/app/modules/msp-core/components/moving-information/moving-information.component.html
src/app/modules/msp-core/components/moving-information/moving-information.component.ts
src/app/modules/request-acl/pages/request-letter/request-letter.component.html
src/index.html

As requested by Ernesto, change from country-only dropdown, to province *and* country text field
>## Old:
>## New:
---

MSPE-219: Update province/country field for temps

---

src/app/modules/account/pages/home/home.component.html

DEA11Y-10: Adjust link to MSP how-to-apply site

---

src/app/modules/account/components/update-request/update-request.component.html
src/app/modules/msp-core/components/support-documents/support-documents.component.html
src/app/modules/request-acl/pages/request-letter/request-letter.component.html

Made the subheadings consistent, lowered them to h3's as per Ernesto's request

DEA11Y-13: Lower doc subheadings

---

src/app/modules/msp-core/components/moving-information/moving-information.component.html
src/app/modules/msp-core/components/support-documents/support-documents.component.html

Changes tip boxes styles for support documents and moving information

DEA11Y-11 (Additional)

---

src/app/modules/account/components/moving-information/moving-information.component.html

>## Old version:
>## New version:

DEAM-498: Adjust date labels for 12 and 6 months

---

src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.html

Adjust supp benefit text notice

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/modules/account/pages/sending/sending.component.ts
src/app/modules/assistance/pages/authorize-submit/authorize-submit.component.spec.ts
src/app/modules/assistance/pages/authorize-submit/authorize-submit.component.ts

Refreshing on assistance will return you to home and clear the in progress application, navigating back after a submission will do the same. Adjusted account similarly to navigate home rather than the landing page when navigating back

DEF-208: Assistance navigation issues

---

src/app/modules/msp-core/components/support-documents/support-documents.component.html
src/app/styles/overrides.scss

Hi,
I would like to ask for you code review. I've updated style for tip box. Please see the attached screenshot below:
Regards,
Cyril

DEA11Y-5-update

---

src/app/styles/additions.scss

DEA11Y-32: Add missing focus/active effect

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/account/components/moving-information/moving-information.component.ts

Hi,
I've fixed the functional issue that Ernesto found in the Return Date where it shows valid dates even though it supposed to show errors. Attached below are the screenshots for the fix:
BEFORE:
AFTER:
Regards,
Cyril

DEA11Y-28: Add Spouse - filed required flag

---

src/app/modules/account/components/moving-information/moving-information.component.html
src/app/modules/benefit/pages/authorize-submit/authorize-submit.component.html
src/app/modules/benefit/pages/financial-info/prepare.component.html
src/app/modules/benefit/pages/financial-info/tax-year/tax-year.component.html
src/app/modules/enrolment/pages/child-info/child-info.component.html
src/app/modules/msp-core/components/moving-information/moving-information.component.html

>### Examples of some that were previously missing

DEA11Y-21: Add missing aria-requireds, error msgs

---

src/app/app.component.html

No change in appearance, no automatic axe warnings

DEA11Y-38: Remove nav tag from footer as per EM request

---

src/app/modules/account/models/account.model.ts
src/app/modules/account/pages/home/home.component.ts
src/app/modules/account/pages/sending/sending.component.ts
src/app/modules/account/services/msp-account-data.service.ts
src/app/modules/account/services/msp-api-account.service.ts
src/app/services/msp-data.service.ts

Since I am unable to reproduce the problem locally or in test, this update will confirm that the default payload is what is being submitted and logged in production database.

DEAM-507: Updated the default payload submission gender to Female

---

src/app/modules/account/services/msp-account-data.service.ts
src/app/services/msp-data.service.ts

Please review the removal of the getFakeAccountChangeApplication() methods and they are not being used anywhere in the code base.

DEAM-509: Removed getFakeAccountChangeApplication() methods.

---

src/app/app.component.ts
src/app/modules/benefit/components/personal-details-retro-suppben/personal-details-retro-suppben.component.html
src/app/modules/benefit/components/personal-details-retro-suppben/personal-details-retro-suppben.component.ts

To test the previous issue, on test upload an image that is too small, proceed through the application and submit. You can do the same with too many images that would be altogether too large, or by refreshing after uploading an image.

DEAM-510: Add error handling for suppben uploads, refresh

---

package-lock.json
src/app/pages/landing/landing.component.html
src/app/pages/landing/landing.component.scss

Minor cosmetic change
>## Before:
>## After:

Fix landing page layout

---

src/app/services/msp-data.service.ts

To see the previous bug, navigate to the test deployment, start an account change application and then navigate directly to /msp

Check images before foreach

---

src/app/modules/account/pages/child-info/add-child/add-child.component.html
src/app/modules/msp-core/components/support-documents/support-documents.component.html

Hi everyone,
Minor updates for the h3 tags as per Ernesto's request. I would like to ask for your quick code review.
Thank you,
Cyril

DEA11Y-50-updated

---

src/app/modules/msp-core/components/review-card/review-card.component.html
src/app/modules/msp-core/components/review-card/review-card.component.ts

Hi there,
I've added changes for the Edit Icon accessibility in the Review Page. I would like to ask for your short code review.
Thank you,
Cyril

DEA11Y-54-updated

---

src/app/modules/account/pages/home/home.component.ts
src/app/modules/account/services/msp-api-account.service.ts

Add back the address change request

---

src/app/modules/account/pages/confirmation/confirmation.component.html
src/app/modules/account/pages/review/review.component.html
src/app/modules/msp-core/components/review-card/review-card.component.html

Hi,
I've added a minor updated for DEA11Y-55 (Removed the aria-hidden for both Print and Edit icons). It still needs to be tested in the screen reader to check if the screen reader reads the icons.
Regards,
Cyril

DEA11Y-55-update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, and other templates adapted from the other bcgov repos, like these:
Codes of Conduct
[MOH ERX Code of Conduct](https://github.com/bcgov/moh-eRx/blob/dev/CODE_OF_CONDUCT.md)
[MOH SMK Code of Conduct](https://github.com/bcgov/smk-moh/blob/qa/CODE_OF_CONDUCT.md)
[MOH PLR FHIR Code of Conduct](https://github.com/bcgov/moh-plr-fhir/blob/master/CODE_OF_CONDUCT.md)
Contributing Guidelines
[MOH ERX Contributing](https://github.com/bcgov/moh-eRx/blob/dev/CONTRIBUTING.md)
[MOH SMK Contributing](https://github.com/bcgov/smk-moh/blob/qa/CONTRIBUTING.md)
[MOH PLR FHIR Contributing](https://github.com/bcgov/moh-plr-fhir/blob/master/CONTRIBUTING.md)
Issue Templates
[MOH SMK Feature Req Template](https://raw.githubusercontent.com/bcgov/smk-moh/qa/.github/ISSUE_TEMPLATE …

Chores and housekeeping

---

src/app/modules/account/pages/authorize/authorize.component.spec.ts
src/app/modules/account/pages/home/home.component.spec.ts
src/app/modules/account/pages/home/home.component.ts
src/app/modules/assistance/components/assist-cra-document/assist-cra-document.component.spec.ts
src/app/modules/enrolment/pages/authorize/authorize.component.spec.ts
src/app/modules/request-acl/pages/request-letter/request-letter.component.spec.ts
src/app/modules/request-acl/pages/request-letter/request-letter.component.ts

Prevents resubmission of address change requests made on Account Change home page
Do you like the new PR template?

Update address change req to send once only

---

package-lock.json
package.json
src/version.GENERATED.ts

Incremented the application version from v3.3.2 to v3.3.3 in package.json, package-lock.json and version.GENERATED.ts

Updated the application version from v3.3.2 to v3.3.3
